version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: always

networks:
  monitoring:
    driver: bridge
