name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: |
        docker pull eremark/booking-project

    - name: Run Trivy Vulnerability Scan
      run: |
        docker run --rm -v /tmp:/tmp aquasec/trivy --exit-code 1 --severity HIGH,CRITICAL --no-progress eremark/booking-project
