 stages:
  - build
  - scan
  - deploy

 build:
  stage: build
  script:
    - docker build -t eremark/booking-docker .
    - docker push eremark/booking-docker

 scan:
  stage: scan
  image: owasp/zap2docker-stable
  script:
    - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://your_website_url -r zap_report.html
  artifacts:
    paths:
      - zap_report.html
      
 
  deploy:
   stage: deploy
    script:
    - docker-compose up -d



      
