name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Deploy to AWS using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run OWASP ZAP vulnerability scan
        run: |
          docker run --rm owasp/zap2docker-stable zap-full-scan.py -t http://booking.pp.ua

      - name: Deploy Prometheus and Grafana for monitoring
        run: |
          docker-compose -f monitoring/docker-compose.yml up -d

      - name: Monitor system performance
        run: |
          docker exec -it prometheus_container_name curl http://localhost:9090/metrics
