name: Deploy Booking Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build Docker image
      run: docker build -t sidannlev/booking-project:latest .

    - name: Push Docker image
      run: docker push sidannlev/booking-project:latest

    - name: Deploy the container on AWS
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<YOUR_EC2_PUBLIC_IP> << EOF
        docker pull sidannlev/booking-project:latest
        docker stop booking-container || true
        docker rm booking-container || true
        docker run -d --name booking-container -p 80:80 sidannlev/booking-project:latest
        EOF

        jobs:
        build_and_scan:
        runs-on: ubuntu-latest

          steps:
        - name: Checkout repository
          uses: actions/checkout@v2
 
        - name: Build Docker image
         run: docker build -t my-image .

        - name: Scan Docker image for vulnerabilities with Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-x86_64.tar.gz | tar xz -C /usr/local/bin
          trivy image my-image
