name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    name: OWASP ZAP Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://boking.pp.ua' # Замени на свой реальный URL
          fail_action: true
          rules_file_name: '.zap/rules.tsv'

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: report_html.html
