name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker tag my-app eremark/booking-website:latest && docker push eremark/booking-website:latest

      - name: Deploy to AWS using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run OWASP ZAP vulnerability scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://booking.pp.ua -r zap_report.html
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}

      - name: Deploy Prometheus and Grafana for monitoring
        run: |
          docker-compose -f monitoring/docker-compose.yml up -d

      - name: Monitor system performance
        run: |
          curl http://localhost:9090/metrics || echo "Prometheus metrics endpoint is unavailable"

      - name: Send alert if Prometheus is down
        run: |
          if ! curl -s http://localhost:9090/-/ready | grep "Prometheus is Ready"; then
            echo "Prometheus is down!" | mail -s "Alert: Prometheus Down" ${{ secrets.ALERT_EMAIL }}
          fi
