name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build Docker Image
      run: docker build -t eremark/booking-project:latest .

    - name: Scan Docker Image for Vulnerabilities with Trivy
      run: |
        # Установим Trivy
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.39.0/trivy_0.39.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin

        # Сканируем на уязвимости
        trivy image eremark/booking-project:latest

    - name: Push Docker Image to DockerHub
      run: docker push eremark/booking-project:latest

    - name: Set up SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Docker Container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} << 'EOF'
          docker pull eremark/booking-project:latest
          docker stop booking-project-container || true
          docker rm booking-project-container || true
          docker run -d --name booking-project-container -p 80:80 eremark/booking-project:latest
        EOF
